### ISSUE TITLE
Annotations of behaviors

### ISSUE THREAD

**Issue by lgoue** [behavioral-data/BOLT#1]
Are you planning to make your annotations of client and therapist behaviors available?
Thank you,

**Comment by ash-shar** [comment]
Thank you for your interest in our work! We plan to release our datasets and annotations later this month. Will let you know once they are out.

**Comment by Hongbin-Ze** [comment]
I am very interested in this work, when will the dataset be released?

**Comment by mianzhang** [comment]
Great work! Looking forward to the release of the annotations.

**Comment by kellycyy** [comment]
Hi everyone, we just uploaded the dataset on annotating behavior in ``dataset_finetune``. Let us know if you have further questions! Thanks!
